// app/vs/labyrinthos/page.tsx — comparison landing page targeting "Labyrinthos
// alternative" search traffic. Sister to /vs/raka. See docs/ROADMAP.md. Static
// marketing copy (not reading content), voice doc's "marketing copy" register (§6).
//
// Pricing facts checked 2026-09-03 against Labyrinthos's own App Store IAP
// listing and an independent review: $9.99/mo Premium subscription (also
// $24.99/quarter, $89.99/yr), PLUS a separate pay-per-reading credit system
// (~$0.10/reading), PLUS one-off deck purchases. Premium's headline unlock is
// AI-generated readings, not just lesson customization, so the deterministic-
// vs-AI-generated wedge applies directly here too. Unlike Raka, Labyrinthos's
// free Learn tab (lessons + quizzes) is a genuine, distinct strength worth
// naming fairly rather than eliding. Re-verify pricing before any future edit.

import type { Metadata } from "next";
import Link from "next/link";
import SiteNav from "../../components/SiteNav";
import Footer from "../../components/Footer";
import { SITE_URL } from "../../../lib/site";
import "../styles.css";

const TITLE = "The Tarot Almanac vs. Labyrinthos: A Tarot App Comparison | The Tarot Almanac";
const DESCRIPTION =
  "Labyrinthos teaches you tarot and layers in AI readings by the credit or the month. The Tarot Almanac gives you a fixed card every day, the same way every time, with every reading written by hand. Here's the actual difference, side by side.";

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  alternates: { canonical: `${SITE_URL}/vs/labyrinthos` },
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    url: `${SITE_URL}/vs/labyrinthos`,
    type: "website",
  },
};

const FAQ: { q: string; a: string }[] = [
  {
    q: "Is The Tarot Almanac an alternative to Labyrinthos?",
    a: "Yes, for the daily-reading side of Labyrinthos. Labyrinthos pairs two things: lessons that teach you to read tarot yourself, and AI-generated readings from its mascot, Catssandra, bought by the credit or unlocked by subscription. The Tarot Almanac only does the second kind of thing, a reading handed to you, and does it without AI: your card comes from a fixed formula run on your birthday and the date, the same one every time.",
  },
  {
    q: "What's the actual difference between The Tarot Almanac and Labyrinthos?",
    a: "Labyrinthos's readings are generated by an AI model when you spend a credit or hold a subscription. The Tarot Almanac's aren't generated at all: which card you get is decided by arithmetic, not a model, and you can run that arithmetic by hand and land on the same card the site shows.",
  },
  {
    q: "Does The Tarot Almanac use AI to write your reading?",
    a: "No. Which card you get is decided by a fixed formula, and the text explaining that card was written once, by a person, and reads the same for everyone who lands on it. Nothing on the page was generated for you specifically.",
  },
  {
    q: "Which is cheaper, The Tarot Almanac or Labyrinthos?",
    a: "The Tarot Almanac is a flat $7 a month, unlimited. Labyrinthos's Premium subscription is $9.99 a month ($24.99 a quarter, $89.99 a year), but Labyrinthos also sells readings à la carte through credits, roughly $0.10 a reading, which can come out cheaper than either subscription if you only check in occasionally.",
  },
  {
    q: "Is Labyrinthos better for learning tarot?",
    a: "If what you want is to learn to read the cards yourself, Labyrinthos's free Learn tab, with lessons and quizzes on the Major Arcana, is a real strength and a different job than what The Tarot Almanac does. The Almanac doesn't teach you to read; it hands you the reading, worked out in the open so you can check it, not necessarily so you can reproduce it from memory.",
  },
];

export default function VsLabyrinthosPage() {
  const faqJsonLd = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: FAQ.map((f) => ({
      "@type": "Question",
      name: f.q,
      acceptedAnswer: { "@type": "Answer", text: f.a },
    })),
  };

  return (
    <>
      <SiteNav />
      <main className="vs-wrap">
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} />

        <nav className="vs-crumb">
          <Link href="/">Home</Link> · The Tarot Almanac vs. Labyrinthos
        </nav>

        <p className="vs-eyebrow">Comparison · Tarot Apps</p>
        <h1 className="vs-h1">The Tarot Almanac vs. Labyrinthos</h1>
        <p className="vs-lede">
          Labyrinthos and The Tarot Almanac both give you a card tied to your birthday and a free
          way to start. Labyrinthos adds tarot lessons and an AI reading feature on top; The Tarot
          Almanac does one thing, a fixed reading, without either. Here&rsquo;s where they actually
          line up and where they don&rsquo;t.
        </p>

        <section className="vs-section">
          <h2>Where they agree</h2>
          <p className="vs-subhead">Start with what&rsquo;s actually shared.</p>
          <ul className="vs-agree">
            <li>A tarot card tied to your birthday, not a random draw</li>
            <li>Individual card meanings you can look up on their own</li>
            <li>A free way in before you pay anything</li>
            <li>A monthly subscription for the fuller version</li>
          </ul>
        </section>

        <section className="vs-section">
          <h2>Where they differ</h2>
          <p className="vs-subhead">This is the part worth reading slowly.</p>

          <h3>How the reading gets made</h3>
          <p>
            Labyrinthos&rsquo;s readings come from Catssandra, its AI mascot: spend a credit or hold
            a subscription, and the model generates the interpretation when you ask. The Tarot
            Almanac doesn&rsquo;t generate anything. Your birthday and the date go through a fixed
            formula, the same one every time, and{" "}
            <Link href="/how-it-works" style={{ color: "var(--indigo)" }}>
              you can run that formula by hand
            </Link>{" "}
            and land on the same card the site shows.
          </p>

          <h3>Learning to read, versus having it done for you</h3>
          <p>
            Labyrinthos leads with teaching: a Learn tab with Major Arcana lessons and quizzes, built
            for someone who wants to read tarot themselves. That&rsquo;s a genuinely different job
            from what The Tarot Almanac does. The Almanac doesn&rsquo;t teach you to read the cards.
            It hands you the reading already worked out, open enough to check, not built as a course.
          </p>

          <h3>Who wrote what you&rsquo;re reading</h3>
          <p>
            The Tarot Almanac&rsquo;s card meanings, Bearings, and month and year readings are each
            written once, by a person, and read the same by everyone who lands on that card. Nothing
            you read was assembled for you in the last second. It was written, and it stays.
          </p>

          <h3>Price</h3>
          <div className="vs-table-wrap">
            <table className="vs-table">
              <caption>Monthly cost, side by side</caption>
              <thead>
                <tr>
                  <th scope="col"></th>
                  <th scope="col">The Tarot Almanac</th>
                  <th scope="col">Labyrinthos</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th scope="row">Free</th>
                  <td>Today&rsquo;s cards, your Bearing, chart preview</td>
                  <td>Daily card, journal, tarot lessons, 33 starter credits</td>
                </tr>
                <tr>
                  <th scope="row">Subscription</th>
                  <td className="vs-yes">$7 / month, unlimited</td>
                  <td>$9.99 / month ($24.99 / quarter, $89.99 / year)</td>
                </tr>
                <tr>
                  <th scope="row">Pay per reading</th>
                  <td>&mdash;</td>
                  <td>About $0.10 / reading via credit packs</td>
                </tr>
                <tr>
                  <th scope="row">One-off chart</th>
                  <td className="vs-yes">$12, no subscription needed</td>
                  <td>&mdash;</td>
                </tr>
                <tr>
                  <th scope="row">How the reading is made</th>
                  <td className="vs-yes">Fixed arithmetic, checkable by hand</td>
                  <td>Generated by an AI model</td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>

        <section className="vs-section vs-faq">
          <h2>Common questions</h2>
          {FAQ.map((f) => (
            <details key={f.q}>
              <summary>{f.q}</summary>
              <p className="ans">{f.a}</p>
            </details>
          ))}
        </section>

        <section className="vs-teaser">
          <span className="eyebrow">The living almanac</span>
          <h2>See where today places you, no AI involved</h2>
          <p>
            Your Bearing, your day and month and year cards, and the collective card everyone shares
            today, all worked from arithmetic you can check yourself.
          </p>
          <Link href="/today" className="vs-cta-btn">
            Find your cards
          </Link>
        </section>

        <p className="vs-links">
          Related: <Link href="/how-it-works">how the math works</Link> ·{" "}
          <Link href="/tarot-birth-chart">your tarot birth chart</Link> ·{" "}
          <Link href="/bearing">your Bearing</Link> ·{" "}
          <Link href="/tarot">all seventy-eight cards</Link> ·{" "}
          <Link href="/vs/raka">The Tarot Almanac vs. Raka</Link> ·{" "}
          <Link href="/me#subscribe">subscribe for $7/month</Link>
        </p>
      </main>
      <Footer />
    </>
  );
}
